#ifndef COMMANDS_H
#define COMMANDS_H

#define REGISTER_DISPLAY_COMMAND "RD"
#define REGISTER_MODIFY_COMMAND  "RM"
#define MEMORY_DISPLAY_COMMAND   "MD"
#define MEMORY_MODIFY_COMMAND = "MM";
#define BLOCK_FILL_COMMAND = "BF";
#define RUN_COMMAND = "RUN";
#define CALL_COMMAND = "CALL";
#define IOMAP_COMMAND = "IOMAP";
#define IOUNMAP_COMMAND = "IOUNMAP";
#define SEGMENT_OUT_COMMAND = "SEGMENT";
#define LCD_PRINT_COMMAND = "LCD";



#endif
